Upgrading Maven Java version to 15. Still works on:
 - command line: JavaFX 15.0.1 and Java 15.0.1
 - IntelliJ IDEA runner: JavaFX 15.0.1 and Java 15.0.1

Does not work for:

 - command line: JavaFX 15.0.1 and Java 11.0.9.1
 - Maven tool window

Not surprisingly, Maven can't compile against Java 15 if JAVA_HOME is JDK 11, command line failure is:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project javafx-maven-archetype: Fatal error compiling: error: release version 15 not supported -> [Help 1]

Similarly (but more confusingly) the error from the Maven Tool Window is:

    Error occurred during initialization of boot layer
    java.lang.module.FindException: Error reading module: /Users/trisha/Documents/Projects/trishagee/javafx-maven-archetype/target/classes
    Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 59.0
    [ERROR] Command execution failed.

It's using Java 11 to run the JavaFX app even though it calls the process with:

    /Users/trisha/Library/Java/JavaVirtualMachines/openjdk-15.0.1/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Users/trisha/Documents/Projects/trishagee/javafx-maven-archetype ....